### PR TITLE
Update testing macro to update-current-env

### PR DESCRIPTION
**Pull request by jaidetree**
Previously, the testing macro would update a *testing-contexts* dynamic var, but the APIs around for stringifying testing-context would read from the current-env.

Given the official cljs impl updates the current-env, this PR applies the same approach.

### CODE REVIEW

**Comment by borkdude** [comment]
Just to double-check, did you test this with nbb locally?

**Comment by borkdude** [comment]
yes

**Comment by borkdude** [comment]
what you could also do is make a fork of sci.configs and then make a candidate PR for nbb based on your fork of sci.configs which tests the change, and after that, we merge it into sci.configs

**Comment by jaidetree** [comment]
I'll give that a shot. Also looks like my formatter added more noise than desired. Going to try again first to mitigate that.

**Comment by jaidetree** [comment]
Created babashka/nbb#359 for testing. Also did test it locally:

```
Testing jaide.test

FAIL in (simple-test) (/Users/j/projects/nbb/test.cljs:10)
If you see this the testing macro is working
expected: (= (+ 1 1) 3)
  actual: (not (= 2 3))

Ran 1 tests containing 1 assertions.
1 failures, 0 errors.
```

**Comment by borkdude** [comment]
I guess now you can update your nbb PR to use the newest sci.configs and then we'll merge that

**Comment by jaidetree** [comment]
> I guess now you can update your nbb PR to use the newest sci.configs and then we'll merge that

Done. Thanks so much!

**Pull request merged**
