### PR TITLE
add promesa/future in namespace

### PR DESCRIPTION
**Pull request by avelino**
ref: https://github.com/babashka/nbb/issues/282

### CODE REVIEW

**Comment by borkdude** [comment]
Since `future` is a macro we have to copy the source and also add the things it expands to (`thread-call`) if it's not in here yet. I think it would be good to add a test for it.

**Comment by borkdude** [comment]
Tests are failing because of:

> and also add the things it expands to (thread-call) if it's not in here yet

**Comment by borkdude** [comment]
Can you merge with master? I bumped the JVM version for the promesa tests

**Comment by avelino** [comment]
> Can you merge with master? I bumped the JVM version for the promesa tests

@borkdude I don't understand the error you gave, can you help me?

```
 :cause promesa/exec/ConcurrencyLimiter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by borkdude** [comment]
@avelino This means that the promesa library was compiled using Java 11 but we used Java 8 in CI. The .class file format changed in Java 11. I upgraded to Java 11 on master, this is why I recommending merging master into your PR branch

**Comment by avelino** [comment]
@borkdude sync to master branch

**Comment by borkdude** [comment]
@avelino I decided to help you finish things off a bit in a different PR which is now on main, since I needed this config myself ;-)

**Pull request closed without merging**
