### PR TITLE
Add reagent functions track and class-names

### PR DESCRIPTION
**Pull request by eccentric-j**
- Add the class-names function from reagent
- Add the track function from reagent
- Adds the make-track from ratom which backs the track function

### CODE REVIEW

**Comment by eccentric-j** [comment]
Worth noting this is untested currently, there a good way to test this with nbb?

**Comment by borkdude** [comment]
@eccentric-j I added a test suite now which runs on CI. I'll try to add a reagent test and then you can attempt to add one? I also have some reagent tests in nbb, I believe, which we can update after updating this.

**Comment by eccentric-j** [comment]
> 

Sounds good to me. Thanks!

**Comment by borkdude** [comment]
@eccentric-j Done

**Comment by borkdude** [comment]
I'll just merge this and optionally you can add tests later

**Comment by eccentric-j** [comment]
Thanks. Came down with Covid on Sunday, trying to rest up and recover first. Apologies on the inconvenience 😅

**Comment by borkdude** [comment]
Not necessary :) Get well soon!

**Pull request merged**
