### PR TITLE
Add clojure.core

### PR DESCRIPTION
**Pull request by Oddsor**
Add new namespace that includes new functions added to clojure.core in version 1.11.

Also add tests verifying that functions are properly included.

### CODE REVIEW

**Comment by Oddsor** [comment]
Continuation on this issue reported for Jet: https://github.com/borkdude/jet/issues/137

**Comment by borkdude** [comment]
Thanks. My proposal would be to split up clojure 1.11 into a separate namespace so you can load the namespaces you wish to use based on the clojure version you're allowed to use. If we stuff 1.12 stuff in there as well, but you're forced to use 1.11 you can't use the extras namespace anymore. Does that make sense?

**Comment by Oddsor** [comment]
Yes, that makes sense!
What would be a decent naming scheme? `clojure.core.1-11` or `clojure.core-1-11`? 🤔

**Comment by borkdude** [comment]
I'd say `clojure-1-11`

**Comment by Oddsor** [comment]
I also changed the namespace's "api" back to `namespaces`, as it might make sense to expand that definition to include `clojure.math` as well eventually?
https://clojure.github.io/clojure/#clojure.math

**Comment by borkdude** [comment]
Thanks!

**Pull request merged**
