### PR TITLE
WIP: promesa: add `done?`

### PR DESCRIPTION
**Pull request by avelino**
could not resolve symbol: `p/done?`
it is in the documentation that this "method" exists https://github.com/babashka/nbb/blob/main/doc/api.md#promesacore

### CODE REVIEW

**Comment by borkdude** [comment]
This doesn't exist for CLJS anymore, since you can't inspect the state of a promise in CLJS.

**Comment by avelino** [comment]
oops, sorry
why don't you let the tests run automatically?

**Comment by borkdude** [comment]
What do you mean? They are run automatically.

Screenshot 2022-11-24 at 14 01 48

Maybe I should ask you: why don't you run the tests locally first, before making a PR ;)

**Comment by avelino** [comment]
@borkdude did not run after this commit:
https://github.com/babashka/sci.configs/pull/16/commits/c72c7bf022eacd481ef3b273fe65b65fc7af40f1

**Comment by borkdude** [comment]
It did?

Screenshot 2022-11-24 at 15 11 29

**Comment by borkdude** [comment]
You can also see that here https://github.com/babashka/sci.configs/actions/runs/3540775251/jobs/5944233179

**Comment by avelino** [comment]
```
 :cause Unable to resolve var: done? in this context at line 175 /home/runner/work/sci.configs/sci.configs/src/sci/configs/funcool/promesa.cljs
```

`done?` change to `p/done?` [in this commit](https://github.com/babashka/sci.configs/commit/c72c7bf022eacd481ef3b273fe65b65fc7af40f1)

**Comment by borkdude** [comment]
Yes.... and when you go to the red cross sign, you will see that the tests still failed.

Screenshot 2022-11-24 at 15 23 22

**Pull request closed without merging**
