### PR TITLE
Re-frame simplification

### PR DESCRIPTION
**Pull request by borkdude**
@bolivier Made a simplification. Since re-frame has no macros AFAIK, we can use `sci/copy-ns` in this case.

### CODE REVIEW

**Comment by bolivier** [comment]
Sweet!

**Comment by borkdude** [comment]
@bolivier Was there a reason you wanted to have this in sci.configs? I remember talking about this with someone, maybe in the context of scittle, but I don't remember it exactly.

**Comment by bolivier** [comment]
For Scittle, yeah.  I'm working on a project and realized it'd be simpler to manage the state with re-frame compared to plain reagent. 

I have a branch of Scittle where it's working.  I was planning to open a PR there next, but I can skip that if you don't want to include it.

**Comment by borkdude** [comment]
@bolivier Yes please :)

**Pull request merged**
