### PR TITLE
Re frame alpha config

### PR DESCRIPTION
**Pull request by kimo-k**
Re-frame has a new `re-frame.alpha` ns since 1.4.0. Upgraded re-frame and integrated the alpha ns.

### CODE REVIEW

**Comment by borkdude** [comment]
@kimo-k I don't understand adding `.alpha` in namespace names. Does this mean it shall be removed later once re-frame decides that namespace becomes beta or production-worthy? And then this will be removed from sci.configs which will mean breaking changes for everyone who uses it? Isn't a main idea of Clojure to never have breaking changes?
I'd rather not disappoint my users by later removing the alpha namespace.

**Comment by kimo-k** [comment]
Hey, I hadn't thought of that perspective. From our end, I can say alpha is not going to be removed any time soon.

Do you think this would cause breakage for people who *don't* import `re-frame.alpha` in their app code? If not, a case might be made that anyone who imports an `alpha` accepts tacitly that it could break on upgrade, or really, any time.

**Comment by borkdude** [comment]
@kimo-k Once your publish, your stuck with it because users rely on it. I don't want to break users. 
And with that in mind: with this PR, the alpha namespace becomes part of the re-frame bundle of e.g. scittle, there is no way to separate them out. Two options:
- We can wait until the alpha stuff comes out of alpha
- Put the re-frame.alpha SCI config stuff in a separate _optional_ namespace such that scittle can make it an _optional_ asset, such that it won't affect the normal re-frame plugin size

**Comment by kimo-k** [comment]
> Once your publish, you're stuck with it because users rely on it

This seems hard to agree with. *To rely on an alpha* - isn't this a contradiction in terms? That said, you made a high-level analysis that I may not fully understand. Also with the bundling options and artifact size, I'm not sure what the ramifications are. Are you sure the impact would be high enough to matter?

For my part, I'll try to answer this more directly:

> And then this will be removed from sci.configs which will mean breaking changes for everyone who uses it? Isn't a main idea of Clojure to never have breaking changes?

AFAICT, `alpha` namespaces constitute the exception which makes this principle practical to uphold. A place where "breaking changes" *are* justified by the use-case. In our case, we intend `re-frame.alpha` to be something users can try out, so they can give feedback. We need a SCI config so that we can [demonstrate the alpha features](https://day8.github.io/re-frame/Flows/). That said, I'm not a tooling expert, so maybe there's a better approach that I'm missing.

> Put the re-frame.alpha SCI config stuff in a separate optional namespace such that scittle can make it an optional asset, such that it won't affect the normal re-frame plugin size

I'll have to do some research & figure out how this would look in practice.

**Comment by borkdude** [comment]
Many people rely on `clojure.spec.alpha`. The Clojure team would never remove this since many Clojure programs would fall over. I'd say just don't make the same mistake.

**Comment by kimo-k** [comment]
> Does this mean it shall be removed later once re-frame decides that namespace becomes beta or production-worthy?

Also, in case it matters: once any features pass alpha, they'll merge into `re-frame.core`. We won't ever provide user-facing API in `re-frame.flow`, for instance. `re-frame.core` is a monolith, for better or worse.

**Comment by kimo-k** [comment]
Okay, gave it a try. I assume it's still okay to use `sci/copy-ns`, even though reagent-dom-server does something else.

**Comment by borkdude** [comment]
@kimo-k If you try running the playground, then you'll see that it doesn't work yet over there since the configuration must still be merged in here:

https://github.com/babashka/sci.configs/blob/91c8eb918c80edaa0c1440070023a05b662538aa/playground/src/playground.cljs#L60

Can you run this locally and verify that it works after doing so? The playground will be automatically updated after merge here:
https://babashka.org/sci.configs/

**Comment by borkdude** [comment]
Sorry for closing, accidentally hit the button

**Comment by kimo-k** [comment]
Fixed & tested.

Screenshot_2023-11-22_14-39-04

**Comment by borkdude** [comment]
Awesome, thanks!

**Pull request merged**
