### PR TITLE
add reagent `track!` and `dispose!`

### PR DESCRIPTION
**Pull request by rgkirch**
The test currently doesn't actually work.

### CODE REVIEW

**Comment by rgkirch** [comment]
I expect that commenting out `(r/dispose! click-count-tracker)` would fail the test but it doesn't. Needs work.

**Comment by borkdude** [comment]
Does it work with the code outside of SCI?

**Comment by rgkirch** [comment]
I haven't tested that yet.

**Comment by rgkirch** [comment]
```clojure

(ns sandbox.app
  (:require [reagent.core :as r]
            [reagent.dom :as rdom]))


(def click-count (r/atom 1))

(add-watch click-count (gensym) (fn [k r o n] (println "click-count: " n)))

(def integral (r/atom 0))

(add-watch integral (gensym) (fn [k r o n] (println "integral: " n)))

(def click-count-tracker (r/track! (fn integrate []
                                     (println (str "(swap! integral + " @click-count ")"))
                                     (swap! integral + @click-count))))

(defn counting-component []
  [:div @integral])

(defn init []
  (rdom/render [counting-component] (js/document.getElementById "app"))

  (swap! click-count inc)

  (r/dispose! click-count-tracker)

  (swap! click-count inc))
```
```
(swap! integral + 1)
integral:  1
click-count:  2
click-count:  3
```

```clojure

(ns sandbox.app
  (:require [reagent.core :as r]
            [reagent.dom :as rdom]))


(def click-count (r/atom 1))

(add-watch click-count (gensym) (fn [k r o n] (println "click-count: " n)))

(def integral (r/atom 0))

(add-watch integral (gensym) (fn [k r o n] (println "integral: " n)))

(def click-count-tracker (r/track! (fn integrate []
                                     (println (str "(swap! integral + " @click-count ")"))
                                     (swap! integral + @click-count))))

(defn counting-component []
  [:div @integral])

(defn init []
  (rdom/render [counting-component] (js/document.getElementById "app"))

  (swap! click-count inc)

  (swap! click-count inc))
```
```
(swap! integral + 1)
integral:  1
click-count:  2
click-count:  3
(swap! integral + 3)
integral:  4
```

**Comment by borkdude** [comment]
Btw, I'm fine with just adding these functions. Since they are just functions, I don't see why they would behave differently inside SCI than outside SCI...

**Comment by rgkirch** [comment]
Ok. Should I just remove the test?

**Comment by borkdude** [comment]
Fine with me

**Pull request merged**
